{
    "openapi": "3.0.0",
    "info": {
        "title": "Backend-Test-Telkom",
        "version": "1.0.0"
    },
    "paths": {
        "/api/conversations": {
            "get": {
                "tags": [
                    "Conversation"
                ],
                "summary": "Get user chat history",
                "operationId": "8570a315aa9db86f4ed4055c675cb14d",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "To get sepesific category by ID",
                        "required": false
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "To get paginated data per page",
                        "required": false
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": true,
                                    "message": "Get category successfull",
                                    "data": []
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": false,
                                    "message": "Validation errors",
                                    "error_code": 422,
                                    "data": {
                                        "errors": {
                                            "email": "<Error Messages>"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthenticated Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": false,
                                    "message": "Unauthenticated",
                                    "error_code": 401,
                                    "data": []
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": false,
                                    "message": "<Error Messages>",
                                    "error_code": 500,
                                    "data": []
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/sendMessage": {
            "post": {
                "tags": [
                    "Send Message"
                ],
                "summary": "Send new message",
                "operationId": "071fdc6b43ef0119a2a512d3feb8203e",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "message": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "message": "Hi, how are you?"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": true,
                                    "message": "Login successfull",
                                    "data": {
                                        "access_token": "1|IdETcPE3WiErAhHsTlNSXO7YrDNiTnX4taxxxxxx"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": false,
                                    "message": "Validation errors",
                                    "error_code": 422,
                                    "data": {
                                        "errors": {
                                            "email": "<Error Messages>"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthenticated Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": false,
                                    "message": "Unauthenticated",
                                    "error_code": 401,
                                    "data": []
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "error_code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": false,
                                    "message": "<Error Messages>",
                                    "error_code": 500,
                                    "data": []
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "SuccessResult": {
                "title": "Schemas for success response",
                "properties": {
                    "success": {
                        "type": "boolean"
                    },
                    "message": {
                        "type": "string"
                    },
                    "data": {
                        "type": "object"
                    }
                },
                "type": "object"
            },
            "FailedResult": {
                "title": "Schemas for failed response",
                "properties": {
                    "success": {
                        "type": "boolean"
                    },
                    "message": {
                        "type": "string"
                    },
                    "error_code": {
                        "type": "integer"
                    },
                    "data": {
                        "type": "object"
                    }
                },
                "type": "object"
            }
        }
    },
    "tags": [
        {
            "name": "Conversation",
            "description": "API Endpoints Group of Conversation"
        },
        {
            "name": "Send Message",
            "description": "API Endpoints Group of Send Message"
        }
    ]
}